spring.datasource.url=jdbc:postgresql://localhost:5432/db_khqr_merchant_uat
spring.datasource.username=postgres
spring.datasource.password=postgres

app.jwt.secret=LocalDevOnlyJwtSecretKeyLocalDevOnlyJwtSecretKey2026
