spring.datasource.url=jdbc:postgresql://localhost:5432/db_khqr_merchant_uat
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

app.jwt.secret=LocalDevOnlyJwtSecretKeyLocalDevOnlyJwtSecretKey2026
app.jwt.expiration-ms=86400000